services:
  - type: web
    name: world-cup
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: ./dist
        destination: /index.html